// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Private      pgtype.Bool        `json:"private"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatorID    pgtype.UUID        `json:"creator_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RoomMember struct {
	RoomID   pgtype.UUID        `json:"room_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
}
