// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRoomMember(ctx context.Context, arg AddRoomMemberParams) (RoomMember, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMessagesByRoom(ctx context.Context, roomID pgtype.UUID) error
	DeleteRoom(ctx context.Context, id pgtype.UUID) error
	GetMessageByID(ctx context.Context, id pgtype.UUID) (Message, error)
	GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error)
	GetRoomByName(ctx context.Context, name string) (Room, error)
	GetRoomMemberCount(ctx context.Context, roomID pgtype.UUID) (int64, error)
	GetRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]GetRoomMembersRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error)
	ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]ListMessagesByRoomRow, error)
	ListRecentMessagesByRoom(ctx context.Context, arg ListRecentMessagesByRoomParams) ([]ListRecentMessagesByRoomRow, error)
	ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error)
	ListRoomsByCreator(ctx context.Context, arg ListRoomsByCreatorParams) ([]Room, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveRoomMember(ctx context.Context, arg RemoveRoomMemberParams) error
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	// User profile management queries
	UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
