// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoomMember = `-- name: AddRoomMember :one
INSERT INTO room_members (room_id, user_id)
VALUES ($1, $2)
ON CONFLICT (room_id, user_id) DO UPDATE SET joined_at = EXCLUDED.joined_at
RETURNING room_id, user_id, joined_at
`

type AddRoomMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, addRoomMember, arg.RoomID, arg.UserID)
	var i RoomMember
	err := row.Scan(&i.RoomID, &i.UserID, &i.JoinedAt)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (room_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, room_id, user_id, content, created_at
`

type CreateMessageParams struct {
	RoomID  pgtype.UUID `json:"room_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Content string      `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.RoomID, arg.UserID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, private, password_hash, creator_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, private, password_hash, creator_id, created_at
`

type CreateRoomParams struct {
	Name         string      `json:"name"`
	Private      pgtype.Bool `json:"private"`
	PasswordHash pgtype.Text `json:"password_hash"`
	CreatorID    pgtype.UUID `json:"creator_id"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Name,
		arg.Private,
		arg.PasswordHash,
		arg.CreatorID,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Private,
		&i.PasswordHash,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, created_at, updated_at, last_login
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const deleteMessagesByRoom = `-- name: DeleteMessagesByRoom :exec
DELETE FROM messages
WHERE room_id = $1
`

func (q *Queries) DeleteMessagesByRoom(ctx context.Context, roomID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessagesByRoom, roomID)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms
WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, room_id, user_id, content, created_at FROM messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, private, password_hash, creator_id, created_at FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Private,
		&i.PasswordHash,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByName = `-- name: GetRoomByName :one
SELECT id, name, private, password_hash, creator_id, created_at FROM rooms
WHERE name = $1
`

func (q *Queries) GetRoomByName(ctx context.Context, name string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByName, name)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Private,
		&i.PasswordHash,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomMemberCount = `-- name: GetRoomMemberCount :one
SELECT COUNT(*) as count
FROM room_members
WHERE room_id = $1
`

func (q *Queries) GetRoomMemberCount(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getRoomMemberCount, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRoomMembers = `-- name: GetRoomMembers :many
SELECT u.id, u.username, u.email, u.password_hash, u.created_at, u.updated_at, u.last_login, rm.joined_at
FROM room_members rm
JOIN users u ON rm.user_id = u.id
WHERE rm.room_id = $1
ORDER BY rm.joined_at ASC
`

type GetRoomMembersRow struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	JoinedAt     pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) GetRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]GetRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, getRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomMembersRow
	for rows.Next() {
		var i GetRoomMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLogin,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, created_at, updated_at, last_login FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, created_at, updated_at, last_login FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, created_at, updated_at, last_login FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const isRoomMember = `-- name: IsRoomMember :one
SELECT EXISTS(
    SELECT 1 FROM room_members
    WHERE room_id = $1 AND user_id = $2
)
`

type IsRoomMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRoomMember, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMessagesByRoom = `-- name: ListMessagesByRoom :many
SELECT m.id, m.room_id, m.user_id, m.content, m.created_at, u.username, r.name as room_name
FROM messages m
JOIN users u ON m.user_id = u.id
JOIN rooms r ON m.room_id = r.id
WHERE m.room_id = $1
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type ListMessagesByRoomParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListMessagesByRoomRow struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
	RoomName  string             `json:"room_name"`
}

func (q *Queries) ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]ListMessagesByRoomRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByRoom, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByRoomRow
	for rows.Next() {
		var i ListMessagesByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
			&i.RoomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessagesByRoom = `-- name: ListRecentMessagesByRoom :many
SELECT m.id, m.room_id, m.user_id, m.content, m.created_at, u.username, r.name as room_name
FROM messages m
JOIN users u ON m.user_id = u.id
JOIN rooms r ON m.room_id = r.id
WHERE m.room_id = $1
ORDER BY m.created_at DESC
LIMIT $2
`

type ListRecentMessagesByRoomParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	Limit  int32       `json:"limit"`
}

type ListRecentMessagesByRoomRow struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
	RoomName  string             `json:"room_name"`
}

func (q *Queries) ListRecentMessagesByRoom(ctx context.Context, arg ListRecentMessagesByRoomParams) ([]ListRecentMessagesByRoomRow, error) {
	rows, err := q.db.Query(ctx, listRecentMessagesByRoom, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentMessagesByRoomRow
	for rows.Next() {
		var i ListRecentMessagesByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
			&i.RoomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, private, password_hash, creator_id, created_at FROM rooms
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Private,
			&i.PasswordHash,
			&i.CreatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByCreator = `-- name: ListRoomsByCreator :many
SELECT id, name, private, password_hash, creator_id, created_at FROM rooms
WHERE creator_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRoomsByCreatorParams struct {
	CreatorID pgtype.UUID `json:"creator_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListRoomsByCreator(ctx context.Context, arg ListRoomsByCreatorParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsByCreator, arg.CreatorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Private,
			&i.PasswordHash,
			&i.CreatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, created_at, updated_at, last_login FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoomMember = `-- name: RemoveRoomMember :exec
DELETE FROM room_members
WHERE room_id = $1 AND user_id = $2
`

type RemoveRoomMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveRoomMember(ctx context.Context, arg RemoveRoomMemberParams) error {
	_, err := q.db.Exec(ctx, removeRoomMember, arg.RoomID, arg.UserID)
	return err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET name = $2, private = $3, password_hash = $4
WHERE id = $1
RETURNING id, name, private, password_hash, creator_id, created_at
`

type UpdateRoomParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Private      pgtype.Bool `json:"private"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.Private,
		arg.PasswordHash,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Private,
		&i.PasswordHash,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :one
UPDATE users
SET last_login = $2
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, last_login
`

type UpdateUserLastLoginParams struct {
	ID        pgtype.UUID        `json:"id"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLastLogin, arg.ID, arg.LastLogin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, last_login
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const updateUserUsername = `-- name: UpdateUserUsername :one

UPDATE users
SET username = $2
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, last_login
`

type UpdateUserUsernameParams struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
}

// User profile management queries
func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}
